// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NHDefine.proto

package nicehu.pb;

public final class NHDefine {
  private NHDefine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum EGEC
      implements com.google.protobuf.ProtocolMessageEnum {
    EGEC_CORE_SUCCESS(0, 0),
    EGEC_CORE_ERROR(1, 1),
    EGEC_CORE_PROC_ERROR(2, 3),
    EGEC_CORE_NET_ERROR(3, 4),
    EGEC_CORE_DESERIALIZE_ERROR(4, 5),
    EGEC_CORE_DATA_CHECK_FAILD(5, 6),
    EGEC_AUTH_TOKEN_TOKEN_EXPIRED(6, 1001),
    EGEC_AUTH_TOKEN_INCORRECT(7, 1002),
    ;
    
    public static final int EGEC_CORE_SUCCESS_VALUE = 0;
    public static final int EGEC_CORE_ERROR_VALUE = 1;
    public static final int EGEC_CORE_PROC_ERROR_VALUE = 3;
    public static final int EGEC_CORE_NET_ERROR_VALUE = 4;
    public static final int EGEC_CORE_DESERIALIZE_ERROR_VALUE = 5;
    public static final int EGEC_CORE_DATA_CHECK_FAILD_VALUE = 6;
    public static final int EGEC_AUTH_TOKEN_TOKEN_EXPIRED_VALUE = 1001;
    public static final int EGEC_AUTH_TOKEN_INCORRECT_VALUE = 1002;
    
    
    public final int getNumber() { return value; }
    
    public static EGEC valueOf(int value) {
      switch (value) {
        case 0: return EGEC_CORE_SUCCESS;
        case 1: return EGEC_CORE_ERROR;
        case 3: return EGEC_CORE_PROC_ERROR;
        case 4: return EGEC_CORE_NET_ERROR;
        case 5: return EGEC_CORE_DESERIALIZE_ERROR;
        case 6: return EGEC_CORE_DATA_CHECK_FAILD;
        case 1001: return EGEC_AUTH_TOKEN_TOKEN_EXPIRED;
        case 1002: return EGEC_AUTH_TOKEN_INCORRECT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EGEC>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EGEC>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EGEC>() {
            public EGEC findValueByNumber(int number) {
              return EGEC.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nicehu.pb.NHDefine.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final EGEC[] VALUES = {
      EGEC_CORE_SUCCESS, EGEC_CORE_ERROR, EGEC_CORE_PROC_ERROR, EGEC_CORE_NET_ERROR, EGEC_CORE_DESERIALIZE_ERROR, EGEC_CORE_DATA_CHECK_FAILD, EGEC_AUTH_TOKEN_TOKEN_EXPIRED, EGEC_AUTH_TOKEN_INCORRECT, 
    };
    
    public static EGEC valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EGEC(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:nicehu.pb.EGEC)
  }
  
  public enum EGMI
      implements com.google.protobuf.ProtocolMessageEnum {
    EGMI_UNKNOW(0, 0),
    EGMI_EVENT_RESULT(1, 1),
    EGMI_EVENT_TRANSPOND(2, 2),
    EGMI_CLOSE_SOCKET(3, 3),
    EGMI_SERVER_DISCONNECT(4, 51),
    EGMI_LOGIC_REINIT(5, 52),
    EGMI_SERVER_LOGIN_REQ(6, 101),
    EGMI_SERVER_LOGIN_RES(7, 102),
    EGMI_SERVER_LOGIN_CONFIRM(8, 103),
    EGMI_SERVER_SERVERINFO_SYNC(9, 105),
    EGMI_SERVER_RELOAD_CONFIG_REQ(10, 107),
    EGMI_SERVER_RELOAD_CONFIG_RES(11, 108),
    EGMI_SERVER_QUERY_TOKEN_REQ(12, 109),
    EGMI_SERVER_QUERY_TOKEN_RES(13, 110),
    EGMI_CREATE_ACCOUNT_REQ(14, 1001),
    EGMI_CREATE_ACCOUNT_RES(15, 1002),
    EGMI_LOGIN_REQ(16, 1003),
    EGMI_LOGIN_RES(17, 1004),
    EGMI_AUTH_TOKEN_REQ(18, 1005),
    EGMI_AUTH_TOKEN_RES(19, 1006),
    EGMI_QUERY_PLAYER_REQ(20, 1007),
    EGMI_QUERY_PLAYER_RES(21, 1008),
    ;
    
    public static final int EGMI_UNKNOW_VALUE = 0;
    public static final int EGMI_EVENT_RESULT_VALUE = 1;
    public static final int EGMI_EVENT_TRANSPOND_VALUE = 2;
    public static final int EGMI_CLOSE_SOCKET_VALUE = 3;
    public static final int EGMI_SERVER_DISCONNECT_VALUE = 51;
    public static final int EGMI_LOGIC_REINIT_VALUE = 52;
    public static final int EGMI_SERVER_LOGIN_REQ_VALUE = 101;
    public static final int EGMI_SERVER_LOGIN_RES_VALUE = 102;
    public static final int EGMI_SERVER_LOGIN_CONFIRM_VALUE = 103;
    public static final int EGMI_SERVER_SERVERINFO_SYNC_VALUE = 105;
    public static final int EGMI_SERVER_RELOAD_CONFIG_REQ_VALUE = 107;
    public static final int EGMI_SERVER_RELOAD_CONFIG_RES_VALUE = 108;
    public static final int EGMI_SERVER_QUERY_TOKEN_REQ_VALUE = 109;
    public static final int EGMI_SERVER_QUERY_TOKEN_RES_VALUE = 110;
    public static final int EGMI_CREATE_ACCOUNT_REQ_VALUE = 1001;
    public static final int EGMI_CREATE_ACCOUNT_RES_VALUE = 1002;
    public static final int EGMI_LOGIN_REQ_VALUE = 1003;
    public static final int EGMI_LOGIN_RES_VALUE = 1004;
    public static final int EGMI_AUTH_TOKEN_REQ_VALUE = 1005;
    public static final int EGMI_AUTH_TOKEN_RES_VALUE = 1006;
    public static final int EGMI_QUERY_PLAYER_REQ_VALUE = 1007;
    public static final int EGMI_QUERY_PLAYER_RES_VALUE = 1008;
    
    
    public final int getNumber() { return value; }
    
    public static EGMI valueOf(int value) {
      switch (value) {
        case 0: return EGMI_UNKNOW;
        case 1: return EGMI_EVENT_RESULT;
        case 2: return EGMI_EVENT_TRANSPOND;
        case 3: return EGMI_CLOSE_SOCKET;
        case 51: return EGMI_SERVER_DISCONNECT;
        case 52: return EGMI_LOGIC_REINIT;
        case 101: return EGMI_SERVER_LOGIN_REQ;
        case 102: return EGMI_SERVER_LOGIN_RES;
        case 103: return EGMI_SERVER_LOGIN_CONFIRM;
        case 105: return EGMI_SERVER_SERVERINFO_SYNC;
        case 107: return EGMI_SERVER_RELOAD_CONFIG_REQ;
        case 108: return EGMI_SERVER_RELOAD_CONFIG_RES;
        case 109: return EGMI_SERVER_QUERY_TOKEN_REQ;
        case 110: return EGMI_SERVER_QUERY_TOKEN_RES;
        case 1001: return EGMI_CREATE_ACCOUNT_REQ;
        case 1002: return EGMI_CREATE_ACCOUNT_RES;
        case 1003: return EGMI_LOGIN_REQ;
        case 1004: return EGMI_LOGIN_RES;
        case 1005: return EGMI_AUTH_TOKEN_REQ;
        case 1006: return EGMI_AUTH_TOKEN_RES;
        case 1007: return EGMI_QUERY_PLAYER_REQ;
        case 1008: return EGMI_QUERY_PLAYER_RES;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EGMI>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EGMI>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EGMI>() {
            public EGMI findValueByNumber(int number) {
              return EGMI.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nicehu.pb.NHDefine.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final EGMI[] VALUES = {
      EGMI_UNKNOW, EGMI_EVENT_RESULT, EGMI_EVENT_TRANSPOND, EGMI_CLOSE_SOCKET, EGMI_SERVER_DISCONNECT, EGMI_LOGIC_REINIT, EGMI_SERVER_LOGIN_REQ, EGMI_SERVER_LOGIN_RES, EGMI_SERVER_LOGIN_CONFIRM, EGMI_SERVER_SERVERINFO_SYNC, EGMI_SERVER_RELOAD_CONFIG_REQ, EGMI_SERVER_RELOAD_CONFIG_RES, EGMI_SERVER_QUERY_TOKEN_REQ, EGMI_SERVER_QUERY_TOKEN_RES, EGMI_CREATE_ACCOUNT_REQ, EGMI_CREATE_ACCOUNT_RES, EGMI_LOGIN_REQ, EGMI_LOGIN_RES, EGMI_AUTH_TOKEN_REQ, EGMI_AUTH_TOKEN_RES, EGMI_QUERY_PLAYER_REQ, EGMI_QUERY_PLAYER_RES, 
    };
    
    public static EGMI valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EGMI(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:nicehu.pb.EGMI)
  }
  
  public enum EIdType
      implements com.google.protobuf.ProtocolMessageEnum {
    EIT_Unknow(0, 0),
    EIT_Special(1, 1),
    EIT_Item(2, 2),
    ;
    
    public static final int EIT_Unknow_VALUE = 0;
    public static final int EIT_Special_VALUE = 1;
    public static final int EIT_Item_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static EIdType valueOf(int value) {
      switch (value) {
        case 0: return EIT_Unknow;
        case 1: return EIT_Special;
        case 2: return EIT_Item;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EIdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EIdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EIdType>() {
            public EIdType findValueByNumber(int number) {
              return EIdType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nicehu.pb.NHDefine.getDescriptor().getEnumTypes().get(2);
    }
    
    private static final EIdType[] VALUES = {
      EIT_Unknow, EIT_Special, EIT_Item, 
    };
    
    public static EIdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EIdType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:nicehu.pb.EIdType)
  }
  
  public enum EIdSpecial
      implements com.google.protobuf.ProtocolMessageEnum {
    EIS_Unknow(0, 0),
    EIS_Money(1, 1),
    ;
    
    public static final int EIS_Unknow_VALUE = 0;
    public static final int EIS_Money_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static EIdSpecial valueOf(int value) {
      switch (value) {
        case 0: return EIS_Unknow;
        case 1: return EIS_Money;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EIdSpecial>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EIdSpecial>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EIdSpecial>() {
            public EIdSpecial findValueByNumber(int number) {
              return EIdSpecial.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nicehu.pb.NHDefine.getDescriptor().getEnumTypes().get(3);
    }
    
    private static final EIdSpecial[] VALUES = {
      EIS_Unknow, EIS_Money, 
    };
    
    public static EIdSpecial valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EIdSpecial(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:nicehu.pb.EIdSpecial)
  }
  
  public enum EAreaStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    EAS_Unknow(0, 0),
    EAS_Normal(1, 1),
    ;
    
    public static final int EAS_Unknow_VALUE = 0;
    public static final int EAS_Normal_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static EAreaStatus valueOf(int value) {
      switch (value) {
        case 0: return EAS_Unknow;
        case 1: return EAS_Normal;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EAreaStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EAreaStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EAreaStatus>() {
            public EAreaStatus findValueByNumber(int number) {
              return EAreaStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nicehu.pb.NHDefine.getDescriptor().getEnumTypes().get(4);
    }
    
    private static final EAreaStatus[] VALUES = {
      EAS_Unknow, EAS_Normal, 
    };
    
    public static EAreaStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EAreaStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:nicehu.pb.EAreaStatus)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/NHDefine.proto\022\tnicehu.pb*\352\001\n\004EG" +
      "EC\022\025\n\021EGEC_CORE_SUCCESS\020\000\022\023\n\017EGEC_CORE_E" +
      "RROR\020\001\022\030\n\024EGEC_CORE_PROC_ERROR\020\003\022\027\n\023EGEC" +
      "_CORE_NET_ERROR\020\004\022\037\n\033EGEC_CORE_DESERIALI" +
      "ZE_ERROR\020\005\022\036\n\032EGEC_CORE_DATA_CHECK_FAILD" +
      "\020\006\022\"\n\035EGEC_AUTH_TOKEN_TOKEN_EXPIRED\020\351\007\022\036" +
      "\n\031EGEC_AUTH_TOKEN_INCORRECT\020\352\007*\342\004\n\004EGMI\022" +
      "\017\n\013EGMI_UNKNOW\020\000\022\025\n\021EGMI_EVENT_RESULT\020\001\022" +
      "\030\n\024EGMI_EVENT_TRANSPOND\020\002\022\025\n\021EGMI_CLOSE_" +
      "SOCKET\020\003\022\032\n\026EGMI_SERVER_DISCONNECT\0203\022\025\n\021",
      "EGMI_LOGIC_REINIT\0204\022\031\n\025EGMI_SERVER_LOGIN" +
      "_REQ\020e\022\031\n\025EGMI_SERVER_LOGIN_RES\020f\022\035\n\031EGM" +
      "I_SERVER_LOGIN_CONFIRM\020g\022\037\n\033EGMI_SERVER_" +
      "SERVERINFO_SYNC\020i\022!\n\035EGMI_SERVER_RELOAD_" +
      "CONFIG_REQ\020k\022!\n\035EGMI_SERVER_RELOAD_CONFI" +
      "G_RES\020l\022\037\n\033EGMI_SERVER_QUERY_TOKEN_REQ\020m" +
      "\022\037\n\033EGMI_SERVER_QUERY_TOKEN_RES\020n\022\034\n\027EGM" +
      "I_CREATE_ACCOUNT_REQ\020\351\007\022\034\n\027EGMI_CREATE_A" +
      "CCOUNT_RES\020\352\007\022\023\n\016EGMI_LOGIN_REQ\020\353\007\022\023\n\016EG" +
      "MI_LOGIN_RES\020\354\007\022\030\n\023EGMI_AUTH_TOKEN_REQ\020\355",
      "\007\022\030\n\023EGMI_AUTH_TOKEN_RES\020\356\007\022\032\n\025EGMI_QUER" +
      "Y_PLAYER_REQ\020\357\007\022\032\n\025EGMI_QUERY_PLAYER_RES" +
      "\020\360\007*8\n\007EIdType\022\016\n\nEIT_Unknow\020\000\022\017\n\013EIT_Sp" +
      "ecial\020\001\022\014\n\010EIT_Item\020\002*+\n\nEIdSpecial\022\016\n\nE" +
      "IS_Unknow\020\000\022\r\n\tEIS_Money\020\001*-\n\013EAreaStatu" +
      "s\022\016\n\nEAS_Unknow\020\000\022\016\n\nEAS_Normal\020\001B\014B\010NHD" +
      "efineH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
