// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NHMsgAuth.proto

package nicehu.pb;

public final class NHMsgAuth {
  private NHMsgAuth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CreateAccountReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string account = 1;
    boolean hasAccount();
    String getAccount();
    
    // optional string pass = 2;
    boolean hasPass();
    String getPass();
    
    // optional .nicehu.pb.DeviceInfo deviceInfo = 3;
    boolean hasDeviceInfo();
    nicehu.pb.NHMsgBase.DeviceInfo getDeviceInfo();
    nicehu.pb.NHMsgBase.DeviceInfoOrBuilder getDeviceInfoOrBuilder();
  }
  public static final class CreateAccountReq extends
      com.google.protobuf.GeneratedMessage
      implements CreateAccountReqOrBuilder {
    // Use CreateAccountReq.newBuilder() to construct.
    private CreateAccountReq(Builder builder) {
      super(builder);
    }
    private CreateAccountReq(boolean noInit) {}
    
    private static final CreateAccountReq defaultInstance;
    public static CreateAccountReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateAccountReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountReq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private Object account_;
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAccount() {
      Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          account_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pass = 2;
    public static final int PASS_FIELD_NUMBER = 2;
    private Object pass_;
    public boolean hasPass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPass() {
      Object ref = pass_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pass_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPassBytes() {
      Object ref = pass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .nicehu.pb.DeviceInfo deviceInfo = 3;
    public static final int DEVICEINFO_FIELD_NUMBER = 3;
    private nicehu.pb.NHMsgBase.DeviceInfo deviceInfo_;
    public boolean hasDeviceInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public nicehu.pb.NHMsgBase.DeviceInfo getDeviceInfo() {
      return deviceInfo_;
    }
    public nicehu.pb.NHMsgBase.DeviceInfoOrBuilder getDeviceInfoOrBuilder() {
      return deviceInfo_;
    }
    
    private void initFields() {
      account_ = "";
      pass_ = "";
      deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, deviceInfo_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, deviceInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgAuth.CreateAccountReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgAuth.CreateAccountReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountReq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountReq_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgAuth.CreateAccountReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
        } else {
          deviceInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgAuth.CreateAccountReq.getDescriptor();
      }
      
      public nicehu.pb.NHMsgAuth.CreateAccountReq getDefaultInstanceForType() {
        return nicehu.pb.NHMsgAuth.CreateAccountReq.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgAuth.CreateAccountReq build() {
        nicehu.pb.NHMsgAuth.CreateAccountReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgAuth.CreateAccountReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgAuth.CreateAccountReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgAuth.CreateAccountReq buildPartial() {
        nicehu.pb.NHMsgAuth.CreateAccountReq result = new nicehu.pb.NHMsgAuth.CreateAccountReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pass_ = pass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (deviceInfoBuilder_ == null) {
          result.deviceInfo_ = deviceInfo_;
        } else {
          result.deviceInfo_ = deviceInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgAuth.CreateAccountReq) {
          return mergeFrom((nicehu.pb.NHMsgAuth.CreateAccountReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgAuth.CreateAccountReq other) {
        if (other == nicehu.pb.NHMsgAuth.CreateAccountReq.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasPass()) {
          setPass(other.getPass());
        }
        if (other.hasDeviceInfo()) {
          mergeDeviceInfo(other.getDeviceInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              account_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pass_ = input.readBytes();
              break;
            }
            case 26: {
              nicehu.pb.NHMsgBase.DeviceInfo.Builder subBuilder = nicehu.pb.NHMsgBase.DeviceInfo.newBuilder();
              if (hasDeviceInfo()) {
                subBuilder.mergeFrom(getDeviceInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDeviceInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string account = 1;
      private Object account_ = "";
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAccount() {
        Object ref = account_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccount(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      void setAccount(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
      }
      
      // optional string pass = 2;
      private Object pass_ = "";
      public boolean hasPass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPass() {
        Object ref = pass_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pass_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPass(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
        return this;
      }
      public Builder clearPass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pass_ = getDefaultInstance().getPass();
        onChanged();
        return this;
      }
      void setPass(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
      }
      
      // optional .nicehu.pb.DeviceInfo deviceInfo = 3;
      private nicehu.pb.NHMsgBase.DeviceInfo deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          nicehu.pb.NHMsgBase.DeviceInfo, nicehu.pb.NHMsgBase.DeviceInfo.Builder, nicehu.pb.NHMsgBase.DeviceInfoOrBuilder> deviceInfoBuilder_;
      public boolean hasDeviceInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public nicehu.pb.NHMsgBase.DeviceInfo getDeviceInfo() {
        if (deviceInfoBuilder_ == null) {
          return deviceInfo_;
        } else {
          return deviceInfoBuilder_.getMessage();
        }
      }
      public Builder setDeviceInfo(nicehu.pb.NHMsgBase.DeviceInfo value) {
        if (deviceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceInfo_ = value;
          onChanged();
        } else {
          deviceInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setDeviceInfo(
          nicehu.pb.NHMsgBase.DeviceInfo.Builder builderForValue) {
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = builderForValue.build();
          onChanged();
        } else {
          deviceInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeDeviceInfo(nicehu.pb.NHMsgBase.DeviceInfo value) {
        if (deviceInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              deviceInfo_ != nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance()) {
            deviceInfo_ =
              nicehu.pb.NHMsgBase.DeviceInfo.newBuilder(deviceInfo_).mergeFrom(value).buildPartial();
          } else {
            deviceInfo_ = value;
          }
          onChanged();
        } else {
          deviceInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearDeviceInfo() {
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
          onChanged();
        } else {
          deviceInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public nicehu.pb.NHMsgBase.DeviceInfo.Builder getDeviceInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDeviceInfoFieldBuilder().getBuilder();
      }
      public nicehu.pb.NHMsgBase.DeviceInfoOrBuilder getDeviceInfoOrBuilder() {
        if (deviceInfoBuilder_ != null) {
          return deviceInfoBuilder_.getMessageOrBuilder();
        } else {
          return deviceInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          nicehu.pb.NHMsgBase.DeviceInfo, nicehu.pb.NHMsgBase.DeviceInfo.Builder, nicehu.pb.NHMsgBase.DeviceInfoOrBuilder> 
          getDeviceInfoFieldBuilder() {
        if (deviceInfoBuilder_ == null) {
          deviceInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              nicehu.pb.NHMsgBase.DeviceInfo, nicehu.pb.NHMsgBase.DeviceInfo.Builder, nicehu.pb.NHMsgBase.DeviceInfoOrBuilder>(
                  deviceInfo_,
                  getParentForChildren(),
                  isClean());
          deviceInfo_ = null;
        }
        return deviceInfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.CreateAccountReq)
    }
    
    static {
      defaultInstance = new CreateAccountReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.CreateAccountReq)
  }
  
  public interface CreateAccountResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
  }
  public static final class CreateAccountRes extends
      com.google.protobuf.GeneratedMessage
      implements CreateAccountResOrBuilder {
    // Use CreateAccountRes.newBuilder() to construct.
    private CreateAccountRes(Builder builder) {
      super(builder);
    }
    private CreateAccountRes(boolean noInit) {}
    
    private static final CreateAccountRes defaultInstance;
    public static CreateAccountRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateAccountRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountRes_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.CreateAccountRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgAuth.CreateAccountRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgAuth.CreateAccountResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountRes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_CreateAccountRes_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgAuth.CreateAccountRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgAuth.CreateAccountRes.getDescriptor();
      }
      
      public nicehu.pb.NHMsgAuth.CreateAccountRes getDefaultInstanceForType() {
        return nicehu.pb.NHMsgAuth.CreateAccountRes.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgAuth.CreateAccountRes build() {
        nicehu.pb.NHMsgAuth.CreateAccountRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgAuth.CreateAccountRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgAuth.CreateAccountRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgAuth.CreateAccountRes buildPartial() {
        nicehu.pb.NHMsgAuth.CreateAccountRes result = new nicehu.pb.NHMsgAuth.CreateAccountRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgAuth.CreateAccountRes) {
          return mergeFrom((nicehu.pb.NHMsgAuth.CreateAccountRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgAuth.CreateAccountRes other) {
        if (other == nicehu.pb.NHMsgAuth.CreateAccountRes.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.CreateAccountRes)
    }
    
    static {
      defaultInstance = new CreateAccountRes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.CreateAccountRes)
  }
  
  public interface LoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string account = 1;
    boolean hasAccount();
    String getAccount();
    
    // optional string pass = 2;
    boolean hasPass();
    String getPass();
    
    // optional .nicehu.pb.DeviceInfo deviceInfo = 3;
    boolean hasDeviceInfo();
    nicehu.pb.NHMsgBase.DeviceInfo getDeviceInfo();
    nicehu.pb.NHMsgBase.DeviceInfoOrBuilder getDeviceInfoOrBuilder();
    
    // optional string randomSeed = 4;
    boolean hasRandomSeed();
    String getRandomSeed();
  }
  public static final class LoginReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginReqOrBuilder {
    // Use LoginReq.newBuilder() to construct.
    private LoginReq(Builder builder) {
      super(builder);
    }
    private LoginReq(boolean noInit) {}
    
    private static final LoginReq defaultInstance;
    public static LoginReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginReq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private Object account_;
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAccount() {
      Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          account_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pass = 2;
    public static final int PASS_FIELD_NUMBER = 2;
    private Object pass_;
    public boolean hasPass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPass() {
      Object ref = pass_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pass_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPassBytes() {
      Object ref = pass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .nicehu.pb.DeviceInfo deviceInfo = 3;
    public static final int DEVICEINFO_FIELD_NUMBER = 3;
    private nicehu.pb.NHMsgBase.DeviceInfo deviceInfo_;
    public boolean hasDeviceInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public nicehu.pb.NHMsgBase.DeviceInfo getDeviceInfo() {
      return deviceInfo_;
    }
    public nicehu.pb.NHMsgBase.DeviceInfoOrBuilder getDeviceInfoOrBuilder() {
      return deviceInfo_;
    }
    
    // optional string randomSeed = 4;
    public static final int RANDOMSEED_FIELD_NUMBER = 4;
    private Object randomSeed_;
    public boolean hasRandomSeed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getRandomSeed() {
      Object ref = randomSeed_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          randomSeed_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRandomSeedBytes() {
      Object ref = randomSeed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        randomSeed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      account_ = "";
      pass_ = "";
      deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
      randomSeed_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, deviceInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRandomSeedBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, deviceInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRandomSeedBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgAuth.LoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgAuth.LoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginReq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginReq_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgAuth.LoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
        } else {
          deviceInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        randomSeed_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgAuth.LoginReq.getDescriptor();
      }
      
      public nicehu.pb.NHMsgAuth.LoginReq getDefaultInstanceForType() {
        return nicehu.pb.NHMsgAuth.LoginReq.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgAuth.LoginReq build() {
        nicehu.pb.NHMsgAuth.LoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgAuth.LoginReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgAuth.LoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgAuth.LoginReq buildPartial() {
        nicehu.pb.NHMsgAuth.LoginReq result = new nicehu.pb.NHMsgAuth.LoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pass_ = pass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (deviceInfoBuilder_ == null) {
          result.deviceInfo_ = deviceInfo_;
        } else {
          result.deviceInfo_ = deviceInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.randomSeed_ = randomSeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgAuth.LoginReq) {
          return mergeFrom((nicehu.pb.NHMsgAuth.LoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgAuth.LoginReq other) {
        if (other == nicehu.pb.NHMsgAuth.LoginReq.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasPass()) {
          setPass(other.getPass());
        }
        if (other.hasDeviceInfo()) {
          mergeDeviceInfo(other.getDeviceInfo());
        }
        if (other.hasRandomSeed()) {
          setRandomSeed(other.getRandomSeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              account_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pass_ = input.readBytes();
              break;
            }
            case 26: {
              nicehu.pb.NHMsgBase.DeviceInfo.Builder subBuilder = nicehu.pb.NHMsgBase.DeviceInfo.newBuilder();
              if (hasDeviceInfo()) {
                subBuilder.mergeFrom(getDeviceInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDeviceInfo(subBuilder.buildPartial());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              randomSeed_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string account = 1;
      private Object account_ = "";
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAccount() {
        Object ref = account_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccount(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      void setAccount(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
      }
      
      // optional string pass = 2;
      private Object pass_ = "";
      public boolean hasPass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPass() {
        Object ref = pass_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pass_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPass(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
        return this;
      }
      public Builder clearPass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pass_ = getDefaultInstance().getPass();
        onChanged();
        return this;
      }
      void setPass(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
      }
      
      // optional .nicehu.pb.DeviceInfo deviceInfo = 3;
      private nicehu.pb.NHMsgBase.DeviceInfo deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          nicehu.pb.NHMsgBase.DeviceInfo, nicehu.pb.NHMsgBase.DeviceInfo.Builder, nicehu.pb.NHMsgBase.DeviceInfoOrBuilder> deviceInfoBuilder_;
      public boolean hasDeviceInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public nicehu.pb.NHMsgBase.DeviceInfo getDeviceInfo() {
        if (deviceInfoBuilder_ == null) {
          return deviceInfo_;
        } else {
          return deviceInfoBuilder_.getMessage();
        }
      }
      public Builder setDeviceInfo(nicehu.pb.NHMsgBase.DeviceInfo value) {
        if (deviceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceInfo_ = value;
          onChanged();
        } else {
          deviceInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setDeviceInfo(
          nicehu.pb.NHMsgBase.DeviceInfo.Builder builderForValue) {
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = builderForValue.build();
          onChanged();
        } else {
          deviceInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeDeviceInfo(nicehu.pb.NHMsgBase.DeviceInfo value) {
        if (deviceInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              deviceInfo_ != nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance()) {
            deviceInfo_ =
              nicehu.pb.NHMsgBase.DeviceInfo.newBuilder(deviceInfo_).mergeFrom(value).buildPartial();
          } else {
            deviceInfo_ = value;
          }
          onChanged();
        } else {
          deviceInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearDeviceInfo() {
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = nicehu.pb.NHMsgBase.DeviceInfo.getDefaultInstance();
          onChanged();
        } else {
          deviceInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public nicehu.pb.NHMsgBase.DeviceInfo.Builder getDeviceInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDeviceInfoFieldBuilder().getBuilder();
      }
      public nicehu.pb.NHMsgBase.DeviceInfoOrBuilder getDeviceInfoOrBuilder() {
        if (deviceInfoBuilder_ != null) {
          return deviceInfoBuilder_.getMessageOrBuilder();
        } else {
          return deviceInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          nicehu.pb.NHMsgBase.DeviceInfo, nicehu.pb.NHMsgBase.DeviceInfo.Builder, nicehu.pb.NHMsgBase.DeviceInfoOrBuilder> 
          getDeviceInfoFieldBuilder() {
        if (deviceInfoBuilder_ == null) {
          deviceInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              nicehu.pb.NHMsgBase.DeviceInfo, nicehu.pb.NHMsgBase.DeviceInfo.Builder, nicehu.pb.NHMsgBase.DeviceInfoOrBuilder>(
                  deviceInfo_,
                  getParentForChildren(),
                  isClean());
          deviceInfo_ = null;
        }
        return deviceInfoBuilder_;
      }
      
      // optional string randomSeed = 4;
      private Object randomSeed_ = "";
      public boolean hasRandomSeed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getRandomSeed() {
        Object ref = randomSeed_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          randomSeed_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRandomSeed(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        randomSeed_ = value;
        onChanged();
        return this;
      }
      public Builder clearRandomSeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        randomSeed_ = getDefaultInstance().getRandomSeed();
        onChanged();
        return this;
      }
      void setRandomSeed(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        randomSeed_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.LoginReq)
    }
    
    static {
      defaultInstance = new LoginReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.LoginReq)
  }
  
  public interface LoginResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
    
    // optional int32 accountId = 2;
    boolean hasAccountId();
    int getAccountId();
    
    // optional string token = 3;
    boolean hasToken();
    String getToken();
    
    // optional int32 lastAreaId = 4 [default = -1];
    boolean hasLastAreaId();
    int getLastAreaId();
    
    // repeated .nicehu.pb.Area areas = 5;
    java.util.List<nicehu.pb.NHMsgBase.Area> 
        getAreasList();
    nicehu.pb.NHMsgBase.Area getAreas(int index);
    int getAreasCount();
    java.util.List<? extends nicehu.pb.NHMsgBase.AreaOrBuilder> 
        getAreasOrBuilderList();
    nicehu.pb.NHMsgBase.AreaOrBuilder getAreasOrBuilder(
        int index);
  }
  public static final class LoginRes extends
      com.google.protobuf.GeneratedMessage
      implements LoginResOrBuilder {
    // Use LoginRes.newBuilder() to construct.
    private LoginRes(Builder builder) {
      super(builder);
    }
    private LoginRes(boolean noInit) {}
    
    private static final LoginRes defaultInstance;
    public static LoginRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginRes_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    // optional int32 accountId = 2;
    public static final int ACCOUNTID_FIELD_NUMBER = 2;
    private int accountId_;
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getAccountId() {
      return accountId_;
    }
    
    // optional string token = 3;
    public static final int TOKEN_FIELD_NUMBER = 3;
    private Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 lastAreaId = 4 [default = -1];
    public static final int LASTAREAID_FIELD_NUMBER = 4;
    private int lastAreaId_;
    public boolean hasLastAreaId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getLastAreaId() {
      return lastAreaId_;
    }
    
    // repeated .nicehu.pb.Area areas = 5;
    public static final int AREAS_FIELD_NUMBER = 5;
    private java.util.List<nicehu.pb.NHMsgBase.Area> areas_;
    public java.util.List<nicehu.pb.NHMsgBase.Area> getAreasList() {
      return areas_;
    }
    public java.util.List<? extends nicehu.pb.NHMsgBase.AreaOrBuilder> 
        getAreasOrBuilderList() {
      return areas_;
    }
    public int getAreasCount() {
      return areas_.size();
    }
    public nicehu.pb.NHMsgBase.Area getAreas(int index) {
      return areas_.get(index);
    }
    public nicehu.pb.NHMsgBase.AreaOrBuilder getAreasOrBuilder(
        int index) {
      return areas_.get(index);
    }
    
    private void initFields() {
      result_ = 0;
      accountId_ = 0;
      token_ = "";
      lastAreaId_ = -1;
      areas_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAreasCount(); i++) {
        if (!getAreas(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, accountId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, lastAreaId_);
      }
      for (int i = 0; i < areas_.size(); i++) {
        output.writeMessage(5, areas_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, accountId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, lastAreaId_);
      }
      for (int i = 0; i < areas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, areas_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgAuth.LoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgAuth.LoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgAuth.LoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginRes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgAuth.internal_static_nicehu_pb_LoginRes_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgAuth.LoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAreasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        lastAreaId_ = -1;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (areasBuilder_ == null) {
          areas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          areasBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgAuth.LoginRes.getDescriptor();
      }
      
      public nicehu.pb.NHMsgAuth.LoginRes getDefaultInstanceForType() {
        return nicehu.pb.NHMsgAuth.LoginRes.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgAuth.LoginRes build() {
        nicehu.pb.NHMsgAuth.LoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgAuth.LoginRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgAuth.LoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgAuth.LoginRes buildPartial() {
        nicehu.pb.NHMsgAuth.LoginRes result = new nicehu.pb.NHMsgAuth.LoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastAreaId_ = lastAreaId_;
        if (areasBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            areas_ = java.util.Collections.unmodifiableList(areas_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.areas_ = areas_;
        } else {
          result.areas_ = areasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgAuth.LoginRes) {
          return mergeFrom((nicehu.pb.NHMsgAuth.LoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgAuth.LoginRes other) {
        if (other == nicehu.pb.NHMsgAuth.LoginRes.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasLastAreaId()) {
          setLastAreaId(other.getLastAreaId());
        }
        if (areasBuilder_ == null) {
          if (!other.areas_.isEmpty()) {
            if (areas_.isEmpty()) {
              areas_ = other.areas_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAreasIsMutable();
              areas_.addAll(other.areas_);
            }
            onChanged();
          }
        } else {
          if (!other.areas_.isEmpty()) {
            if (areasBuilder_.isEmpty()) {
              areasBuilder_.dispose();
              areasBuilder_ = null;
              areas_ = other.areas_;
              bitField0_ = (bitField0_ & ~0x00000010);
              areasBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAreasFieldBuilder() : null;
            } else {
              areasBuilder_.addAllMessages(other.areas_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        for (int i = 0; i < getAreasCount(); i++) {
          if (!getAreas(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              token_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastAreaId_ = input.readInt32();
              break;
            }
            case 42: {
              nicehu.pb.NHMsgBase.Area.Builder subBuilder = nicehu.pb.NHMsgBase.Area.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAreas(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 accountId = 2;
      private int accountId_ ;
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAccountId() {
        return accountId_;
      }
      public Builder setAccountId(int value) {
        bitField0_ |= 0x00000002;
        accountId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string token = 3;
      private Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
      }
      
      // optional int32 lastAreaId = 4 [default = -1];
      private int lastAreaId_ = -1;
      public boolean hasLastAreaId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getLastAreaId() {
        return lastAreaId_;
      }
      public Builder setLastAreaId(int value) {
        bitField0_ |= 0x00000008;
        lastAreaId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastAreaId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastAreaId_ = -1;
        onChanged();
        return this;
      }
      
      // repeated .nicehu.pb.Area areas = 5;
      private java.util.List<nicehu.pb.NHMsgBase.Area> areas_ =
        java.util.Collections.emptyList();
      private void ensureAreasIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          areas_ = new java.util.ArrayList<nicehu.pb.NHMsgBase.Area>(areas_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          nicehu.pb.NHMsgBase.Area, nicehu.pb.NHMsgBase.Area.Builder, nicehu.pb.NHMsgBase.AreaOrBuilder> areasBuilder_;
      
      public java.util.List<nicehu.pb.NHMsgBase.Area> getAreasList() {
        if (areasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(areas_);
        } else {
          return areasBuilder_.getMessageList();
        }
      }
      public int getAreasCount() {
        if (areasBuilder_ == null) {
          return areas_.size();
        } else {
          return areasBuilder_.getCount();
        }
      }
      public nicehu.pb.NHMsgBase.Area getAreas(int index) {
        if (areasBuilder_ == null) {
          return areas_.get(index);
        } else {
          return areasBuilder_.getMessage(index);
        }
      }
      public Builder setAreas(
          int index, nicehu.pb.NHMsgBase.Area value) {
        if (areasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAreasIsMutable();
          areas_.set(index, value);
          onChanged();
        } else {
          areasBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAreas(
          int index, nicehu.pb.NHMsgBase.Area.Builder builderForValue) {
        if (areasBuilder_ == null) {
          ensureAreasIsMutable();
          areas_.set(index, builderForValue.build());
          onChanged();
        } else {
          areasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAreas(nicehu.pb.NHMsgBase.Area value) {
        if (areasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAreasIsMutable();
          areas_.add(value);
          onChanged();
        } else {
          areasBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAreas(
          int index, nicehu.pb.NHMsgBase.Area value) {
        if (areasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAreasIsMutable();
          areas_.add(index, value);
          onChanged();
        } else {
          areasBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAreas(
          nicehu.pb.NHMsgBase.Area.Builder builderForValue) {
        if (areasBuilder_ == null) {
          ensureAreasIsMutable();
          areas_.add(builderForValue.build());
          onChanged();
        } else {
          areasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAreas(
          int index, nicehu.pb.NHMsgBase.Area.Builder builderForValue) {
        if (areasBuilder_ == null) {
          ensureAreasIsMutable();
          areas_.add(index, builderForValue.build());
          onChanged();
        } else {
          areasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAreas(
          java.lang.Iterable<? extends nicehu.pb.NHMsgBase.Area> values) {
        if (areasBuilder_ == null) {
          ensureAreasIsMutable();
          super.addAll(values, areas_);
          onChanged();
        } else {
          areasBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAreas() {
        if (areasBuilder_ == null) {
          areas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          areasBuilder_.clear();
        }
        return this;
      }
      public Builder removeAreas(int index) {
        if (areasBuilder_ == null) {
          ensureAreasIsMutable();
          areas_.remove(index);
          onChanged();
        } else {
          areasBuilder_.remove(index);
        }
        return this;
      }
      public nicehu.pb.NHMsgBase.Area.Builder getAreasBuilder(
          int index) {
        return getAreasFieldBuilder().getBuilder(index);
      }
      public nicehu.pb.NHMsgBase.AreaOrBuilder getAreasOrBuilder(
          int index) {
        if (areasBuilder_ == null) {
          return areas_.get(index);  } else {
          return areasBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends nicehu.pb.NHMsgBase.AreaOrBuilder> 
           getAreasOrBuilderList() {
        if (areasBuilder_ != null) {
          return areasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(areas_);
        }
      }
      public nicehu.pb.NHMsgBase.Area.Builder addAreasBuilder() {
        return getAreasFieldBuilder().addBuilder(
            nicehu.pb.NHMsgBase.Area.getDefaultInstance());
      }
      public nicehu.pb.NHMsgBase.Area.Builder addAreasBuilder(
          int index) {
        return getAreasFieldBuilder().addBuilder(
            index, nicehu.pb.NHMsgBase.Area.getDefaultInstance());
      }
      public java.util.List<nicehu.pb.NHMsgBase.Area.Builder> 
           getAreasBuilderList() {
        return getAreasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          nicehu.pb.NHMsgBase.Area, nicehu.pb.NHMsgBase.Area.Builder, nicehu.pb.NHMsgBase.AreaOrBuilder> 
          getAreasFieldBuilder() {
        if (areasBuilder_ == null) {
          areasBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              nicehu.pb.NHMsgBase.Area, nicehu.pb.NHMsgBase.Area.Builder, nicehu.pb.NHMsgBase.AreaOrBuilder>(
                  areas_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          areas_ = null;
        }
        return areasBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.LoginRes)
    }
    
    static {
      defaultInstance = new LoginRes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.LoginRes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_CreateAccountReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_CreateAccountReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_CreateAccountRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_CreateAccountRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_LoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_LoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_LoginRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_LoginRes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/NHMsgAuth.proto\022\tnicehu.pb\032\025prot" +
      "o/NHMsgBase.proto\"\\\n\020CreateAccountReq\022\017\n" +
      "\007account\030\001 \001(\t\022\014\n\004pass\030\002 \001(\t\022)\n\ndeviceIn" +
      "fo\030\003 \001(\0132\025.nicehu.pb.DeviceInfo\"\"\n\020Creat" +
      "eAccountRes\022\016\n\006result\030\001 \002(\005\"h\n\010LoginReq\022" +
      "\017\n\007account\030\001 \001(\t\022\014\n\004pass\030\002 \001(\t\022)\n\ndevice" +
      "Info\030\003 \001(\0132\025.nicehu.pb.DeviceInfo\022\022\n\nran" +
      "domSeed\030\004 \001(\t\"t\n\010LoginRes\022\016\n\006result\030\001 \002(" +
      "\005\022\021\n\taccountId\030\002 \001(\005\022\r\n\005token\030\003 \001(\t\022\026\n\nl" +
      "astAreaId\030\004 \001(\005:\002-1\022\036\n\005areas\030\005 \003(\0132\017.nic",
      "ehu.pb.AreaB\rB\tNHMsgAuthH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nicehu_pb_CreateAccountReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nicehu_pb_CreateAccountReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_CreateAccountReq_descriptor,
              new java.lang.String[] { "Account", "Pass", "DeviceInfo", },
              nicehu.pb.NHMsgAuth.CreateAccountReq.class,
              nicehu.pb.NHMsgAuth.CreateAccountReq.Builder.class);
          internal_static_nicehu_pb_CreateAccountRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_nicehu_pb_CreateAccountRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_CreateAccountRes_descriptor,
              new java.lang.String[] { "Result", },
              nicehu.pb.NHMsgAuth.CreateAccountRes.class,
              nicehu.pb.NHMsgAuth.CreateAccountRes.Builder.class);
          internal_static_nicehu_pb_LoginReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_nicehu_pb_LoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_LoginReq_descriptor,
              new java.lang.String[] { "Account", "Pass", "DeviceInfo", "RandomSeed", },
              nicehu.pb.NHMsgAuth.LoginReq.class,
              nicehu.pb.NHMsgAuth.LoginReq.Builder.class);
          internal_static_nicehu_pb_LoginRes_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_nicehu_pb_LoginRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_LoginRes_descriptor,
              new java.lang.String[] { "Result", "AccountId", "Token", "LastAreaId", "Areas", },
              nicehu.pb.NHMsgAuth.LoginRes.class,
              nicehu.pb.NHMsgAuth.LoginRes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          nicehu.pb.NHMsgBase.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
