// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NHMsgGame.proto

package nicehu.pb;

public final class NHMsgGame {
  private NHMsgGame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerDisconnectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string result = 1;
    boolean hasResult();
    String getResult();
    
    // optional int32 playerId = 2;
    boolean hasPlayerId();
    int getPlayerId();
  }
  public static final class ServerDisconnect extends
      com.google.protobuf.GeneratedMessage
      implements ServerDisconnectOrBuilder {
    // Use ServerDisconnect.newBuilder() to construct.
    private ServerDisconnect(Builder builder) {
      super(builder);
    }
    private ServerDisconnect(boolean noInit) {}
    
    private static final ServerDisconnect defaultInstance;
    public static ServerDisconnect getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServerDisconnect getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ServerDisconnect_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ServerDisconnect_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private Object result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getResult() {
      Object ref = result_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          result_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultBytes() {
      Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 playerId = 2;
    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPlayerId() {
      return playerId_;
    }
    
    private void initFields() {
      result_ = "";
      playerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, playerId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ServerDisconnect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.ServerDisconnect prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.ServerDisconnectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ServerDisconnect_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ServerDisconnect_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.ServerDisconnect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.ServerDisconnect.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.ServerDisconnect getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.ServerDisconnect.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.ServerDisconnect build() {
        nicehu.pb.NHMsgGame.ServerDisconnect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.ServerDisconnect buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.ServerDisconnect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.ServerDisconnect buildPartial() {
        nicehu.pb.NHMsgGame.ServerDisconnect result = new nicehu.pb.NHMsgGame.ServerDisconnect(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerId_ = playerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.ServerDisconnect) {
          return mergeFrom((nicehu.pb.NHMsgGame.ServerDisconnect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.ServerDisconnect other) {
        if (other == nicehu.pb.NHMsgGame.ServerDisconnect.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              result_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string result = 1;
      private Object result_ = "";
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getResult() {
        Object ref = result_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResult(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      void setResult(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
      }
      
      // optional int32 playerId = 2;
      private int playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.ServerDisconnect)
    }
    
    static {
      defaultInstance = new ServerDisconnect(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.ServerDisconnect)
  }
  
  public interface ReturnExceptionSeqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 exceptionSeq = 1;
    boolean hasExceptionSeq();
    int getExceptionSeq();
    
    // required int32 result = 2;
    boolean hasResult();
    int getResult();
  }
  public static final class ReturnExceptionSeq extends
      com.google.protobuf.GeneratedMessage
      implements ReturnExceptionSeqOrBuilder {
    // Use ReturnExceptionSeq.newBuilder() to construct.
    private ReturnExceptionSeq(Builder builder) {
      super(builder);
    }
    private ReturnExceptionSeq(boolean noInit) {}
    
    private static final ReturnExceptionSeq defaultInstance;
    public static ReturnExceptionSeq getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReturnExceptionSeq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ReturnExceptionSeq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ReturnExceptionSeq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 exceptionSeq = 1;
    public static final int EXCEPTIONSEQ_FIELD_NUMBER = 1;
    private int exceptionSeq_;
    public boolean hasExceptionSeq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getExceptionSeq() {
      return exceptionSeq_;
    }
    
    // required int32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getResult() {
      return result_;
    }
    
    private void initFields() {
      exceptionSeq_ = 0;
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasExceptionSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, exceptionSeq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, result_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, exceptionSeq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.ReturnExceptionSeq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.ReturnExceptionSeq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.ReturnExceptionSeqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ReturnExceptionSeq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_ReturnExceptionSeq_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.ReturnExceptionSeq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        exceptionSeq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.ReturnExceptionSeq.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.ReturnExceptionSeq getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.ReturnExceptionSeq.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.ReturnExceptionSeq build() {
        nicehu.pb.NHMsgGame.ReturnExceptionSeq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.ReturnExceptionSeq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.ReturnExceptionSeq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.ReturnExceptionSeq buildPartial() {
        nicehu.pb.NHMsgGame.ReturnExceptionSeq result = new nicehu.pb.NHMsgGame.ReturnExceptionSeq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exceptionSeq_ = exceptionSeq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.ReturnExceptionSeq) {
          return mergeFrom((nicehu.pb.NHMsgGame.ReturnExceptionSeq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.ReturnExceptionSeq other) {
        if (other == nicehu.pb.NHMsgGame.ReturnExceptionSeq.getDefaultInstance()) return this;
        if (other.hasExceptionSeq()) {
          setExceptionSeq(other.getExceptionSeq());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasExceptionSeq()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              exceptionSeq_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              result_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 exceptionSeq = 1;
      private int exceptionSeq_ ;
      public boolean hasExceptionSeq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getExceptionSeq() {
        return exceptionSeq_;
      }
      public Builder setExceptionSeq(int value) {
        bitField0_ |= 0x00000001;
        exceptionSeq_ = value;
        onChanged();
        return this;
      }
      public Builder clearExceptionSeq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exceptionSeq_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 result = 2;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.ReturnExceptionSeq)
    }
    
    static {
      defaultInstance = new ReturnExceptionSeq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.ReturnExceptionSeq)
  }
  
  public interface GC_NotifySeqIdErrorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 errorType = 1;
    boolean hasErrorType();
    int getErrorType();
  }
  public static final class GC_NotifySeqIdError extends
      com.google.protobuf.GeneratedMessage
      implements GC_NotifySeqIdErrorOrBuilder {
    // Use GC_NotifySeqIdError.newBuilder() to construct.
    private GC_NotifySeqIdError(Builder builder) {
      super(builder);
    }
    private GC_NotifySeqIdError(boolean noInit) {}
    
    private static final GC_NotifySeqIdError defaultInstance;
    public static GC_NotifySeqIdError getDefaultInstance() {
      return defaultInstance;
    }
    
    public GC_NotifySeqIdError getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_GC_NotifySeqIdError_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_GC_NotifySeqIdError_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 errorType = 1;
    public static final int ERRORTYPE_FIELD_NUMBER = 1;
    private int errorType_;
    public boolean hasErrorType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrorType() {
      return errorType_;
    }
    
    private void initFields() {
      errorType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasErrorType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.GC_NotifySeqIdError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.GC_NotifySeqIdError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.GC_NotifySeqIdErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_GC_NotifySeqIdError_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_GC_NotifySeqIdError_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.GC_NotifySeqIdError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errorType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.GC_NotifySeqIdError.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.GC_NotifySeqIdError getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.GC_NotifySeqIdError.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.GC_NotifySeqIdError build() {
        nicehu.pb.NHMsgGame.GC_NotifySeqIdError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.GC_NotifySeqIdError buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.GC_NotifySeqIdError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.GC_NotifySeqIdError buildPartial() {
        nicehu.pb.NHMsgGame.GC_NotifySeqIdError result = new nicehu.pb.NHMsgGame.GC_NotifySeqIdError(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorType_ = errorType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.GC_NotifySeqIdError) {
          return mergeFrom((nicehu.pb.NHMsgGame.GC_NotifySeqIdError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.GC_NotifySeqIdError other) {
        if (other == nicehu.pb.NHMsgGame.GC_NotifySeqIdError.getDefaultInstance()) return this;
        if (other.hasErrorType()) {
          setErrorType(other.getErrorType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasErrorType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorType_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 errorType = 1;
      private int errorType_ ;
      public boolean hasErrorType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrorType() {
        return errorType_;
      }
      public Builder setErrorType(int value) {
        bitField0_ |= 0x00000001;
        errorType_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorType_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.GC_NotifySeqIdError)
    }
    
    static {
      defaultInstance = new GC_NotifySeqIdError(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.GC_NotifySeqIdError)
  }
  
  public interface AuthTokenReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string token = 1;
    boolean hasToken();
    String getToken();
  }
  public static final class AuthTokenReq extends
      com.google.protobuf.GeneratedMessage
      implements AuthTokenReqOrBuilder {
    // Use AuthTokenReq.newBuilder() to construct.
    private AuthTokenReq(Builder builder) {
      super(builder);
    }
    private AuthTokenReq(boolean noInit) {}
    
    private static final AuthTokenReq defaultInstance;
    public static AuthTokenReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public AuthTokenReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenReq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.AuthTokenReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.AuthTokenReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenReq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenReq_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.AuthTokenReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.AuthTokenReq.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.AuthTokenReq getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.AuthTokenReq.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.AuthTokenReq build() {
        nicehu.pb.NHMsgGame.AuthTokenReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.AuthTokenReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.AuthTokenReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.AuthTokenReq buildPartial() {
        nicehu.pb.NHMsgGame.AuthTokenReq result = new nicehu.pb.NHMsgGame.AuthTokenReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.AuthTokenReq) {
          return mergeFrom((nicehu.pb.NHMsgGame.AuthTokenReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.AuthTokenReq other) {
        if (other == nicehu.pb.NHMsgGame.AuthTokenReq.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string token = 1;
      private Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.AuthTokenReq)
    }
    
    static {
      defaultInstance = new AuthTokenReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.AuthTokenReq)
  }
  
  public interface AuthTokenResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 2;
    boolean hasResult();
    int getResult();
  }
  public static final class AuthTokenRes extends
      com.google.protobuf.GeneratedMessage
      implements AuthTokenResOrBuilder {
    // Use AuthTokenRes.newBuilder() to construct.
    private AuthTokenRes(Builder builder) {
      super(builder);
    }
    private AuthTokenRes(boolean noInit) {}
    
    private static final AuthTokenRes defaultInstance;
    public static AuthTokenRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public AuthTokenRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenRes_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, result_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.AuthTokenRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.AuthTokenRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.AuthTokenResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenRes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_AuthTokenRes_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.AuthTokenRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.AuthTokenRes.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.AuthTokenRes getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.AuthTokenRes.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.AuthTokenRes build() {
        nicehu.pb.NHMsgGame.AuthTokenRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.AuthTokenRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.AuthTokenRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.AuthTokenRes buildPartial() {
        nicehu.pb.NHMsgGame.AuthTokenRes result = new nicehu.pb.NHMsgGame.AuthTokenRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.AuthTokenRes) {
          return mergeFrom((nicehu.pb.NHMsgGame.AuthTokenRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.AuthTokenRes other) {
        if (other == nicehu.pb.NHMsgGame.AuthTokenRes.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 2;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.AuthTokenRes)
    }
    
    static {
      defaultInstance = new AuthTokenRes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.AuthTokenRes)
  }
  
  public interface QueryPlayerReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class QueryPlayerReq extends
      com.google.protobuf.GeneratedMessage
      implements QueryPlayerReqOrBuilder {
    // Use QueryPlayerReq.newBuilder() to construct.
    private QueryPlayerReq(Builder builder) {
      super(builder);
    }
    private QueryPlayerReq(boolean noInit) {}
    
    private static final QueryPlayerReq defaultInstance;
    public static QueryPlayerReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public QueryPlayerReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerReq_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.QueryPlayerReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.QueryPlayerReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerReq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerReq_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.QueryPlayerReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.QueryPlayerReq.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.QueryPlayerReq getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.QueryPlayerReq.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.QueryPlayerReq build() {
        nicehu.pb.NHMsgGame.QueryPlayerReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.QueryPlayerReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.QueryPlayerReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.QueryPlayerReq buildPartial() {
        nicehu.pb.NHMsgGame.QueryPlayerReq result = new nicehu.pb.NHMsgGame.QueryPlayerReq(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.QueryPlayerReq) {
          return mergeFrom((nicehu.pb.NHMsgGame.QueryPlayerReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.QueryPlayerReq other) {
        if (other == nicehu.pb.NHMsgGame.QueryPlayerReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.QueryPlayerReq)
    }
    
    static {
      defaultInstance = new QueryPlayerReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.QueryPlayerReq)
  }
  
  public interface QueryPlayerResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
    
    // optional .nicehu.pb.Player player = 2;
    boolean hasPlayer();
    nicehu.pb.NHMsgBase.Player getPlayer();
    nicehu.pb.NHMsgBase.PlayerOrBuilder getPlayerOrBuilder();
  }
  public static final class QueryPlayerRes extends
      com.google.protobuf.GeneratedMessage
      implements QueryPlayerResOrBuilder {
    // Use QueryPlayerRes.newBuilder() to construct.
    private QueryPlayerRes(Builder builder) {
      super(builder);
    }
    private QueryPlayerRes(boolean noInit) {}
    
    private static final QueryPlayerRes defaultInstance;
    public static QueryPlayerRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public QueryPlayerRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerRes_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    // optional .nicehu.pb.Player player = 2;
    public static final int PLAYER_FIELD_NUMBER = 2;
    private nicehu.pb.NHMsgBase.Player player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public nicehu.pb.NHMsgBase.Player getPlayer() {
      return player_;
    }
    public nicehu.pb.NHMsgBase.PlayerOrBuilder getPlayerOrBuilder() {
      return player_;
    }
    
    private void initFields() {
      result_ = 0;
      player_ = nicehu.pb.NHMsgBase.Player.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, player_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, player_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nicehu.pb.NHMsgGame.QueryPlayerRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nicehu.pb.NHMsgGame.QueryPlayerRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nicehu.pb.NHMsgGame.QueryPlayerResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerRes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nicehu.pb.NHMsgGame.internal_static_nicehu_pb_QueryPlayerRes_fieldAccessorTable;
      }
      
      // Construct using nicehu.pb.NHMsgGame.QueryPlayerRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (playerBuilder_ == null) {
          player_ = nicehu.pb.NHMsgBase.Player.getDefaultInstance();
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nicehu.pb.NHMsgGame.QueryPlayerRes.getDescriptor();
      }
      
      public nicehu.pb.NHMsgGame.QueryPlayerRes getDefaultInstanceForType() {
        return nicehu.pb.NHMsgGame.QueryPlayerRes.getDefaultInstance();
      }
      
      public nicehu.pb.NHMsgGame.QueryPlayerRes build() {
        nicehu.pb.NHMsgGame.QueryPlayerRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nicehu.pb.NHMsgGame.QueryPlayerRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nicehu.pb.NHMsgGame.QueryPlayerRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nicehu.pb.NHMsgGame.QueryPlayerRes buildPartial() {
        nicehu.pb.NHMsgGame.QueryPlayerRes result = new nicehu.pb.NHMsgGame.QueryPlayerRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nicehu.pb.NHMsgGame.QueryPlayerRes) {
          return mergeFrom((nicehu.pb.NHMsgGame.QueryPlayerRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nicehu.pb.NHMsgGame.QueryPlayerRes other) {
        if (other == nicehu.pb.NHMsgGame.QueryPlayerRes.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              nicehu.pb.NHMsgBase.Player.Builder subBuilder = nicehu.pb.NHMsgBase.Player.newBuilder();
              if (hasPlayer()) {
                subBuilder.mergeFrom(getPlayer());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPlayer(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // optional .nicehu.pb.Player player = 2;
      private nicehu.pb.NHMsgBase.Player player_ = nicehu.pb.NHMsgBase.Player.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          nicehu.pb.NHMsgBase.Player, nicehu.pb.NHMsgBase.Player.Builder, nicehu.pb.NHMsgBase.PlayerOrBuilder> playerBuilder_;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public nicehu.pb.NHMsgBase.Player getPlayer() {
        if (playerBuilder_ == null) {
          return player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      public Builder setPlayer(nicehu.pb.NHMsgBase.Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPlayer(
          nicehu.pb.NHMsgBase.Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePlayer(nicehu.pb.NHMsgBase.Player value) {
        if (playerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              player_ != nicehu.pb.NHMsgBase.Player.getDefaultInstance()) {
            player_ =
              nicehu.pb.NHMsgBase.Player.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = nicehu.pb.NHMsgBase.Player.getDefaultInstance();
          onChanged();
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public nicehu.pb.NHMsgBase.Player.Builder getPlayerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      public nicehu.pb.NHMsgBase.PlayerOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          nicehu.pb.NHMsgBase.Player, nicehu.pb.NHMsgBase.Player.Builder, nicehu.pb.NHMsgBase.PlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              nicehu.pb.NHMsgBase.Player, nicehu.pb.NHMsgBase.Player.Builder, nicehu.pb.NHMsgBase.PlayerOrBuilder>(
                  player_,
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:nicehu.pb.QueryPlayerRes)
    }
    
    static {
      defaultInstance = new QueryPlayerRes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nicehu.pb.QueryPlayerRes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_ServerDisconnect_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_ServerDisconnect_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_ReturnExceptionSeq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_ReturnExceptionSeq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_GC_NotifySeqIdError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_GC_NotifySeqIdError_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_AuthTokenReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_AuthTokenReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_AuthTokenRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_AuthTokenRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_QueryPlayerReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_QueryPlayerReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nicehu_pb_QueryPlayerRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nicehu_pb_QueryPlayerRes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/NHMsgGame.proto\022\tnicehu.pb\032\025prot" +
      "o/NHMsgBase.proto\"4\n\020ServerDisconnect\022\016\n" +
      "\006result\030\001 \001(\t\022\020\n\010playerId\030\002 \001(\005\":\n\022Retur" +
      "nExceptionSeq\022\024\n\014exceptionSeq\030\001 \002(\005\022\016\n\006r" +
      "esult\030\002 \002(\005\"(\n\023GC_NotifySeqIdError\022\021\n\ter" +
      "rorType\030\001 \002(\005\"\035\n\014AuthTokenReq\022\r\n\005token\030\001" +
      " \002(\t\"\036\n\014AuthTokenRes\022\016\n\006result\030\002 \002(\005\"\020\n\016" +
      "QueryPlayerReq\"C\n\016QueryPlayerRes\022\016\n\006resu" +
      "lt\030\001 \002(\005\022!\n\006player\030\002 \001(\0132\021.nicehu.pb.Pla" +
      "yerB\rB\tNHMsgGameH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nicehu_pb_ServerDisconnect_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nicehu_pb_ServerDisconnect_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_ServerDisconnect_descriptor,
              new java.lang.String[] { "Result", "PlayerId", },
              nicehu.pb.NHMsgGame.ServerDisconnect.class,
              nicehu.pb.NHMsgGame.ServerDisconnect.Builder.class);
          internal_static_nicehu_pb_ReturnExceptionSeq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_nicehu_pb_ReturnExceptionSeq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_ReturnExceptionSeq_descriptor,
              new java.lang.String[] { "ExceptionSeq", "Result", },
              nicehu.pb.NHMsgGame.ReturnExceptionSeq.class,
              nicehu.pb.NHMsgGame.ReturnExceptionSeq.Builder.class);
          internal_static_nicehu_pb_GC_NotifySeqIdError_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_nicehu_pb_GC_NotifySeqIdError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_GC_NotifySeqIdError_descriptor,
              new java.lang.String[] { "ErrorType", },
              nicehu.pb.NHMsgGame.GC_NotifySeqIdError.class,
              nicehu.pb.NHMsgGame.GC_NotifySeqIdError.Builder.class);
          internal_static_nicehu_pb_AuthTokenReq_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_nicehu_pb_AuthTokenReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_AuthTokenReq_descriptor,
              new java.lang.String[] { "Token", },
              nicehu.pb.NHMsgGame.AuthTokenReq.class,
              nicehu.pb.NHMsgGame.AuthTokenReq.Builder.class);
          internal_static_nicehu_pb_AuthTokenRes_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_nicehu_pb_AuthTokenRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_AuthTokenRes_descriptor,
              new java.lang.String[] { "Result", },
              nicehu.pb.NHMsgGame.AuthTokenRes.class,
              nicehu.pb.NHMsgGame.AuthTokenRes.Builder.class);
          internal_static_nicehu_pb_QueryPlayerReq_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_nicehu_pb_QueryPlayerReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_QueryPlayerReq_descriptor,
              new java.lang.String[] { },
              nicehu.pb.NHMsgGame.QueryPlayerReq.class,
              nicehu.pb.NHMsgGame.QueryPlayerReq.Builder.class);
          internal_static_nicehu_pb_QueryPlayerRes_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_nicehu_pb_QueryPlayerRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nicehu_pb_QueryPlayerRes_descriptor,
              new java.lang.String[] { "Result", "Player", },
              nicehu.pb.NHMsgGame.QueryPlayerRes.class,
              nicehu.pb.NHMsgGame.QueryPlayerRes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          nicehu.pb.NHMsgBase.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
