//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: proto/NHDefine.proto
namespace nicehu.pb
{
    [global::ProtoBuf.ProtoContract(Name=@"EGEC")]
    public enum EGEC
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_CORE_SUCCESS", Value=0)]
      EGEC_CORE_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_CORE_ERROR", Value=1)]
      EGEC_CORE_ERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_CORE_PROC_ERROR", Value=3)]
      EGEC_CORE_PROC_ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_CORE_NET_ERROR", Value=4)]
      EGEC_CORE_NET_ERROR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_CORE_DESERIALIZE_ERROR", Value=5)]
      EGEC_CORE_DESERIALIZE_ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_CORE_DATA_CHECK_FAILD", Value=6)]
      EGEC_CORE_DATA_CHECK_FAILD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_NET_CONNECTED", Value=11)]
      EGEC_NET_CONNECTED = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_NET_CONNECTING", Value=12)]
      EGEC_NET_CONNECTING = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_NET_NEED_QUERY", Value=13)]
      EGEC_NET_NEED_QUERY = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_NET_DISCONNECTED", Value=14)]
      EGEC_NET_DISCONNECTED = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_NET_CLOSED", Value=15)]
      EGEC_NET_CLOSED = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_AUTH_TOKEN_TOKEN_EXPIRED", Value=1001)]
      EGEC_AUTH_TOKEN_TOKEN_EXPIRED = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGEC_AUTH_TOKEN_INCORRECT", Value=1002)]
      EGEC_AUTH_TOKEN_INCORRECT = 1002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EGMI")]
    public enum EGMI
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_UNKNOW", Value=0)]
      EGMI_UNKNOW = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_EVENT_RESULT", Value=1)]
      EGMI_EVENT_RESULT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_EVENT_TRANSPOND", Value=2)]
      EGMI_EVENT_TRANSPOND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_CLOSE_SOCKET", Value=3)]
      EGMI_CLOSE_SOCKET = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_DISCONNECT", Value=51)]
      EGMI_SERVER_DISCONNECT = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_LOGIC_REINIT", Value=52)]
      EGMI_LOGIC_REINIT = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_LOGIN_REQ", Value=101)]
      EGMI_SERVER_LOGIN_REQ = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_LOGIN_RES", Value=102)]
      EGMI_SERVER_LOGIN_RES = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_LOGIN_CONFIRM", Value=103)]
      EGMI_SERVER_LOGIN_CONFIRM = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_SERVERINFO_SYNC", Value=105)]
      EGMI_SERVER_SERVERINFO_SYNC = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_RELOAD_CONFIG_REQ", Value=107)]
      EGMI_SERVER_RELOAD_CONFIG_REQ = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_RELOAD_CONFIG_RES", Value=108)]
      EGMI_SERVER_RELOAD_CONFIG_RES = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_QUERY_TOKEN_REQ", Value=109)]
      EGMI_SERVER_QUERY_TOKEN_REQ = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_SERVER_QUERY_TOKEN_RES", Value=110)]
      EGMI_SERVER_QUERY_TOKEN_RES = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_CREATE_ACCOUNT_REQ", Value=1001)]
      EGMI_CREATE_ACCOUNT_REQ = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_CREATE_ACCOUNT_RES", Value=1002)]
      EGMI_CREATE_ACCOUNT_RES = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_LOGIN_REQ", Value=1003)]
      EGMI_LOGIN_REQ = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_LOGIN_RES", Value=1004)]
      EGMI_LOGIN_RES = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_AUTH_TOKEN_REQ", Value=1005)]
      EGMI_AUTH_TOKEN_REQ = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_AUTH_TOKEN_RES", Value=1006)]
      EGMI_AUTH_TOKEN_RES = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_QUERY_PLAYER_REQ", Value=1007)]
      EGMI_QUERY_PLAYER_REQ = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGMI_QUERY_PLAYER_RES", Value=1008)]
      EGMI_QUERY_PLAYER_RES = 1008
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EIdType")]
    public enum EIdType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EIT_Unknow", Value=0)]
      EIT_Unknow = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EIT_Special", Value=1)]
      EIT_Special = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EIT_Item", Value=2)]
      EIT_Item = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EIdSpecial")]
    public enum EIdSpecial
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EIS_Unknow", Value=0)]
      EIS_Unknow = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EIS_Money", Value=1)]
      EIS_Money = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EAreaStatus")]
    public enum EAreaStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAS_Unknow", Value=0)]
      EAS_Unknow = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAS_Normal", Value=1)]
      EAS_Normal = 1
    }
  
}