//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: proto/NHMsgAuth.proto
// Note: requires additional types generated from: proto/NHMsgBase.proto
namespace nicehu.pb
{
  [global::ProtoBuf.ProtoContract(Name=@"CreateAccountReq")]
  public partial class CreateAccountReq : global::ProtoBuf.IExtensible
  {
    public CreateAccountReq() {}
    
    private string _account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _pass = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pass
    {
      get { return _pass; }
      set { _pass = value; }
    }
    private nicehu.pb.DeviceInfo _deviceInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deviceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public nicehu.pb.DeviceInfo deviceInfo
    {
      get { return _deviceInfo; }
      set { _deviceInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"CreateAccountRes")]
  public partial class CreateAccountRes : global::ProtoBuf.IExtensible
  {
    public CreateAccountRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _pass = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pass
    {
      get { return _pass; }
      set { _pass = value; }
    }
    private nicehu.pb.DeviceInfo _deviceInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deviceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public nicehu.pb.DeviceInfo deviceInfo
    {
      get { return _deviceInfo; }
      set { _deviceInfo = value; }
    }
    private string _randomSeed = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _accountId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _lastAreaId = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastAreaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int lastAreaId
    {
      get { return _lastAreaId; }
      set { _lastAreaId = value; }
    }
    private readonly global::System.Collections.Generic.List<nicehu.pb.Area> _areas = new global::System.Collections.Generic.List<nicehu.pb.Area>();
    [global::ProtoBuf.ProtoMember(5, Name=@"areas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<nicehu.pb.Area> areas
    {
      get { return _areas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}